import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "../components/Home/Nav";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Onilne Book Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
